/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_kellygod_schoolclient_ndkentry_NativeLoad */

#ifndef _Included_cn_kellygod_schoolclient_ndkentry_NativeLoad
#define _Included_cn_kellygod_schoolclient_ndkentry_NativeLoad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_kellygod_schoolclient_ndkentry_NativeLoad
 * Method:    Login
 * Signature: (Landroid/os/Handler;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_kellygod_schoolclient_ndk_NativeLoad_Login
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
